import {
  BLACK,
  DARK_BLUE,
  DARK_BROWN,
  DARK_GREEN,
  LIGHT_BLUE,
  LIGHT_BROWN,
  LIGHT_GREEN,
  ORANGE_BROWN,
  PURPLE,
  RED,
} from "./colours";

// weights

export const UNDERGROUND_WEIGHT = 0;
export const NARROW_WEIGHT = 4;
export const BORDER_WEIGHT_ADD_ON = 4;
export const WIDE_WEIGHT = 8;

// dashes

export const DASH_PATTERN = "6, 10";

// zoom

export const SOMEWHAT_ZOOMED_IN = 16;
export const VERY_ZOOMED_IN = 18;

// colours

export const BIDIRECTIONAL_COLOUR_LIGHT = LIGHT_GREEN;
export const BIDIRECTIONAL_COLOUR_FULL = DARK_GREEN;
export const UNIDIRECTIONAL_COLOUR_LIGHT = LIGHT_BLUE;
export const UNIDIRECTIONAL_COLOUR_FULL = DARK_BLUE;
export const SHOULDER_COLOUR_LIGHT = LIGHT_BROWN;
export const SHOULDER_COLOUR_FULL = DARK_BROWN;

export const VIDEO_BIDIRECTIONAL_COLOUR = PURPLE;
export const VIDEO_UNIDIRECTIONAL_COLOUR = PURPLE;

export const CLOSED_COLOUR = RED;

export const ELEVATED_BORDER_COLOUR = BLACK;
export const UNDERGROUND_BORDER_COLOUR = ORANGE_BROWN;
