import {
  BLACK,
  CYAN,
  DARK_BLUE,
  DARK_BROWN,
  DARK_GREEN,
  DARK_GREY,
  DARK_PURPLE,
  DARK_YELLOW,
  LIGHT_GREEN,
  LIGHT_GREY,
  LIGHT_PURPLE,
  LIGHT_YELLOW,
  MAGENTA,
  ORANGE_BROWN,
  RED,
} from "./colours";

// weights

export const WEIGHT_NARROW = 4;
export const WEIGHT_WIDE = 8;
export const WEIGHT_UNDERGROUND = 0;
export const WEIGHT_BORDER_ADD_ON = 4;

// dashes

export const DASH_PATTERN = "6, 10";

// zoom

export const ZOOMED_IN_A_BIT = 16;
export const ZOOMED_IN_A_LOT = 18;

// colours

export const COLOUR_COMFORTABLE = DARK_GREEN;
export const COLOUR_COMFORTABLE_ONE_WAY = LIGHT_GREEN;
export const COLOUR_QUIET = DARK_PURPLE;
export const COLOUR_QUIET_ONE_WAY = LIGHT_PURPLE;
export const COLOUR_PAINTED_ONE_WAY = DARK_BLUE;
export const COLOUR_SHARED = DARK_YELLOW;
export const COLOUR_SHARED_ONE_WAY = LIGHT_YELLOW;
export const COLOUR_SHOULDER_ONE_WAY = DARK_BROWN;
export const COLOUR_OTHER = LIGHT_GREY;
export const COLOUR_OTHER_ONE_WAY = DARK_GREY;

export const COLOUR_CLOSED = RED;
export const COLOUR_HIGHLIGHTED = CYAN;
export const COLOUR_VIDEO_SELECTED = MAGENTA;
export const COLOUR_VIDEO_NOT_SELECTED = LIGHT_PURPLE;

export const COLOUR_ELEVATED_BORDER = BLACK;
export const COLOUR_UNDERGROUND_BORDER = ORANGE_BROWN;

// screen

export const WIDTH_BREAKPOINT = 800;
